[tool.bumpversion]
current_version = "0.0.1"

parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]

ignore_missing_version = false
ignore_missing_files = false

tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"

moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "volkit/__init__.py"
search   = '^(?P<indent>\s*)__version__\s*=\s*"{current_version}"\s*$'
replace  = '\g<indent>__version__ = "{new_version}"'
regex    = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search   = '^(?P<indent>\s*)version\s*=\s*"{current_version}"\s*$'
replace  = '\g<indent>version = "{new_version}"'
regex    = true
