repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0   # pick the latest release
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5   # pick the latest tag
    hooks:
      - id: ruff
        args: ["--fix"]   # auto-fix where possible

