name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - name: Configure Poetry
        run: poetry config virtualenvs.create true
      - name: Install deps
        run: poetry install --with dev
      - name: Run tests with coverage
        run: poetry run pytest --cov=volkit --cov-report=xml --cov-report=term-missing
        env:
          PYTHONHASHSEED: "0"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          use_oidc: true
          disable_search: true
          slug: sitmo/volkit
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}


